Test/add tests to slider image component
RibonDAO/interface pull request #317
Opened 2022-07-13 19:57 UTC by Isaac-alencar

# Description
- This Pull Request add tests to `SliderImage`. But I also made some minor improvements on component itself
- improve typing avoiding components with "any" type
- Improvements on storybook adding more assets and a video asset to see how it works with multiple assets

## Does this pull request close any open issues?
- closes #257

2022-07-14 18:04 UTC, leodhb requested changes

2022-07-14 18:04 UTC, leodhb commented on src/components/moleculars/sliders/SliderImage/index.stories.tsx
> +    { imageUrl: "https://img-9gag-fun.9cache.com/photo/a81OBv1_460svvp9.webm" },
Can we use another picsum image here too?

2022-07-14 18:04 UTC, leodhb commented on src/components/moleculars/sliders/SliderImage/index.test.tsx
> +              "https://img-9gag-fun.9cache.com/photo/a81OBv1_460svvp9.webm",
Ditto

2022-07-14 18:18 UTC, leodhb requested changes

2022-07-14 18:18 UTC, leodhb commented on src/components/moleculars/sliders/SliderImage/index.test.tsx
> +              "https://img-9gag-fun.9cache.com/photo/a81OBv1_460svvp9.webm",
Ditto

2022-08-09 00:22 UTC, Isaac-alencar commented
Apologies for delay by EOW I will deliver all changes :)

2024-02-22 17:37 UTC, closed without merging